INSERT INTO STUDENT(FIRST_NAME,LAST_NAME) values ('Tam', '1');
INSERT INTO STUDENT(FIRST_NAME,LAST_NAME) values ('Tam', '2');
INSERT INTO STUDENT(FIRST_NAME,LAST_NAME) values ('Tam', '3');
INSERT INTO STUDENT(FIRST_NAME,LAST_NAME) values ('Tam', '4');
 
 
 
 
 